### ISSUE TITLE
USERSTORY: View home page

### ISSUE THREAD

**Issue by puma13992** [puma13992/digital-patient#1]
As a user I can view the homepage so that I can see the description of the website.

### Acceptance Criteria:

- Display a start screen with information about the purpose of the website

### Tasks:

- [x]  Create the template (HTML) for the base.html
- [x]  Create the template (HTML) for the home.html
- [x] Write a text about the purpose of the website
- [x] Implement the text in the home.html
- [x] Style the home.html with CSS and/or using Bootstrap
- [x] Add URL path

### Story points: 2
