### ISSUE TITLE
USER STORY: Edit personal data

### ISSUE THREAD

**Issue by puma13992** [puma13992/digital-patient#10]
As a registered user I can edit my personal data in my account so that I keep it up to date.

### Acceptance Criteria:

- As a user I can find a button on my profile page to edit my personal data.
- As a user I can edit my personal data, such as name, birthday etc..
- As a user I can set the "I want to be resuscitate" checkbox on or off.
- As a user I can see the edited items.

### Tasks:

- [x] Create working button on the profile page which is lead the user to the personal data page
- [x] Create and style personal data page
- [x] Add the functionality so that the user can edit his/her personal data
- [x] Add URL path

### Story points: 5
