### ISSUE TITLE
USER STORY: Delete doctors

### ISSUE THREAD

**Issue by puma13992** [puma13992/digital-patient#12]
As a registered user I can delete doctors in my account so that I keep it up to date.

### Acceptance Criteria:

- As a user I can delete doctors.
- As a user I can`t see the deleted items anymore.

### Tasks:

- [x] Create working button to delete items
- [x] Add the functionality so that the user can delete doctors
- [x] Add the functionality so that the user can`t see his/her deleted doctors anymore

### Story points: 3
