### ISSUE TITLE
USER STORY: Edit contacts

### ISSUE THREAD

**Issue by puma13992** [puma13992/digital-patient#13]
As a registered user I can edit contacts in my account so that I keep it up to date.

### Acceptance Criteria:

- As a user I can find a button on my profile page to edit contacts.
- As a user I can edit my contacts.
- As a user I can see the edited items.

### Tasks:

- [x] Create working button on the profile page which is lead the user to the my contact page
- [x] Create and style this page
- [x] Add the functionality so that the user can edit his/her contacts
- [x] Add URL path

### Story points: 5
