### ISSUE TITLE
USER STORY: Add doctors

### ISSUE THREAD

**Issue by puma13992** [puma13992/digital-patient#14]
As a registered user I can add doctors in my account so that I keep it up to date.

### Acceptance Criteria:

- As a user I can add doctors.
- As a user I can see the new added items.

### Tasks:

- [x] Create working button to add items
- [x] Add the functionality so that the user can add doctors
- [x] Add the functionality so that the user can see his/her doctors

### Story points: 3
