### ISSUE TITLE
USER STORY: Add contacts

### ISSUE THREAD

**Issue by puma13992** [puma13992/digital-patient#15]
As a registered user I can add contacts in my account so that I keep it up to date.

### Acceptance Criteria:

- As a user I can add contacts.
- As a user I can see the new added items.

### Tasks:

- [x] Create working button to add items
- [x] Add the functionality so that the user can add contacts
- [x] Add the functionality so that the user can see his/her contacts

### Story points: 3
