### ISSUE TITLE
USER STORY: Add diseases and medications

### ISSUE THREAD

**Issue by puma13992** [puma13992/digital-patient#16]
As a registered user I can add (new) diseases and medications in my account so that I keep it up to date.

### Acceptance Criteria:

- As a user I can add pre-existing diseases and medications.
- As a user I can see the new added items.

### Tasks:

- [x] Create working button to add items
- [x] Add the functionality so that the user can add pre-existing diseases and medications
- [x] Add the functionality so that the user can see his/her pre-existing diseases and medications

### Story points: 3
