### ISSUE TITLE
USER STORY: Delete diseases and medications

### ISSUE THREAD

**Issue by puma13992** [puma13992/digital-patient#17]
As a registered user I can delete diseases and medications in my account so that I keep it up to date.

### Acceptance Criteria:

- As a user I can delete pre-existing diseases and medications.
- As a user I can`t see the deleted items anymore.

### Tasks:

- [x] Create working button to delete items
- [x] Add the functionality so that the user can delete pre-existing diseases and medications
- [x] Add the functionality so that the user can`t see his/her deleted pre-existing diseases and medications anymore

### Story points: 3
