### ISSUE TITLE
USER STORY: Delete contacts

### ISSUE THREAD

**Issue by puma13992** [puma13992/digital-patient#18]
As a registered user I can delete contacts in my account so that I keep it up to date.

### Acceptance Criteria:

- As a user I can delete contacts.
- As a user I can`t see the deleted items anymore.

### Tasks:

- [x] Create working button to delete items
- [x] Add the functionality so that the user can delete contacts
- [x] Add the functionality so that the user can`t see his/her deleted contacts anymore

### Story points: 3
