### ISSUE TITLE
USER STORY: Delete account

### ISSUE THREAD

**Issue by puma13992** [puma13992/digital-patient#19]
As a registered user I can delete my account so that I can`t log in anymore.

### Acceptance Criteria:

- As a user I can delete my account if I clicked the button in my profile.
- As a user I can`t login anymore after deleting my account.

### Tasks:

- [x] Create working button to delete account
- [x] Add the functionality so that the user can delete his/her account
- [x] Add the functionality so that the user can`t login anymore after deleting his/her account

### Story points: 3
