### ISSUE TITLE
USER STORY: User registration

### ISSUE THREAD

**Issue by puma13992** [puma13992/digital-patient#2]
As a user I can register on the site so that I can get a login account.

### Acceptance Criteria:

- As a User I can find the register link in the nav bar.
- As a User I can create an account at the register page and choose my credentials.

### Tasks:

- [x] Create a register page using bootstrap 
- [x] Add menu item/correct link in the nav bar
- [x] Add URL path
- [x] Use the allauth library
- [x] Create the functionality for the user to create an account using their name, email and password

### Story points: 5
