### ISSUE TITLE
USER STOR: Edit medication/diseases

### ISSUE THREAD

**Issue by puma13992** [puma13992/digital-patient#27]
As a registered user I can edit my medications/diseases in my account so that I keep it up to date.

### Acceptance Criteria:

- As a user I can find a button on my profile page to edit my medications/diseases 
- As a user I can edit my medications/diseases.
- As a user I can see the edited items.

### Tasks:

- [x] Create working button on the profile page which is lead the user to the medications/diseases page
- [x] Create and style medications/diseases page
- [x] Add the functionality so that the user can edit his/her medications/diseases 
- [x] Add URL path

### Story points: 5
