### ISSUE TITLE
USER STORY: README file

### ISSUE THREAD

**Issue by puma13992** [puma13992/digital-patient#29]
As a user I can find a detailed readme file so that I can read some information about the project.

### Acceptance Criteria:

- As a user I can find a readme file on github.
- As a user I can find information about the project in the readme file.

### Tasks:

- [x] Add information about UX in the readme file
- [x] Add information about user stories in the readme file
- [x] Add information about agile methodology in the readme file
- [x] Add information about design in the readme file
- [x] Add information about features in the readme file
- [x] Add information about used technologies in the readme file
- [x] Add information about testing in the readme file
- [x] Add information about deployment in the readme file
- [x] Add information about credits in the readme file
