### ISSUE TITLE
USER STORY: Navigate the site

### ISSUE THREAD

**Issue by puma13992** [puma13992/digital-patient#3]
As a user I can navigate through the whole website so that I explore the benefit of it.

### Acceptance Criteria:

- As a user I can find the menu on each page.
- As a user I can view the menu and read it's content.
- As a user I can click on the menu items and every item worked.

### Tasks:

- [x] Create navbar (menu) 
- [x] Create menu items
- [x] Create working links for each menu item

### Story points: 2
