### ISSUE TITLE
DEVELOPER STORY: Manual & automated testing

### ISSUE THREAD

**Issue by puma13992** [puma13992/digital-patient#30]
As a developer I test my project so that I can find and fix potential bugs.

### Acceptance Criteria:

- As a developer I set up automated testing.
- As a developer I`ll test the project manually.

### Tasks:

- [x] Setup automated testing for the forms.py, urls.py, models.py & views.py
- [x] Test the project manually and intensively
- [x] Look for bugs 
- [x] Fix found bugs (if possible)
- [x] Note the results in the readme file
