### ISSUE TITLE
USER STORY: Login to account

### ISSUE THREAD

**Issue by puma13992** [puma13992/digital-patient#5]
As a user I can log into my account after registration so that I can change things in it.

### Acceptance Criteria:

- As a user I can find the login item in the nav bar.
- As a user I can click on the login item in the nav bar which goes to the login page.
- As a user I can log in with my login details which I have registered.
- As a user I can see my profile page if I logged in.

### Tasks:

- [x] Create and style the login page
- [x]  Create a login page using bootstrap 
- [x] Add menu item/correct link for login in the nav bar
- [x] Use the allauth library
- [x] Create the functionality for the user to login properly with his/her registered data
- [x] Create and style a page which is shown up after a successful login (profile-page)
- [x] Add menu item/correct link for the profile page in the nav bar which is only shown to user who logged in
- [x] Add URL paths for login page and page after a succesful login
